//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public int details_id { get; set; }
        public int O_id { get; set; }
        public int P_id { get; set; }
        public int Order_qty { get; set; }
        public Nullable<decimal> Order_price { get; set; }
        public Nullable<decimal> Order_total { get; set; }
    
        public virtual C_order_table C_order_table { get; set; }
        public virtual product_table product_table { get; set; }
    }
}
